{{- if .Values.frontend.envoygw.enabled }}
{{- if .Values.frontend.envoygw.httprouteOnly.enabled }}
{{- with .Values.frontend.envoygw.httprouteOnly }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "frontend.envoygw" . }}
spec:
  parentRefs:
    - name: {{ .gatewayRef }}
      namespace: {{ .gatewayNs }}
  hostnames:
    {{- range .hostnames }}
    - {{ . | quote }}
    {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "frontend.fullname" . }}
          port: {{ .Values.frontend.service.port }}
          weight: {{ .Values.frontend.eg.weight }}
{{- end }}
{{- end }}
{{- end }}

