{{- if .Values.frontend.envoygw.enabled }}
{{- if .Values.frontend.envoygw.httpGateway.enabled }}
{{- with .Values.frontend.envoygw.httpGateway }}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .className }}
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .gatewayName }}
spec:
  gatewayClassName: {{ .className }}
  listeners:
  - name: http 
    port: 80
    protocol: HTTP
    allowedRoutes:
      {{- toYaml .allowedRoutes | nindent 6 }}
{{- end }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "frontend.envoygw" . }}
spec:
  parentRefs:
    - name: {{ .Values.frontend.envoygw.httpGateway.gatewayName }}
{{- with .Values.frontend.envoygw.httpGateway }}
  hostnames:
    {{- range .hostnames }}
    - {{ . | quote }}
    {{- end }}
    {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "frontend.fullname" . }}
          port: {{ .Values.frontend.service.port }}
          weight: {{ .Values.frontend.envoygw.httpGateway.weight }}

{{- end }}
{{- end }}

