apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: loki-stack
    app.kubernetes.io/name: promtail
    app.kubernetes.io/version: 2.7.0
  name: loki-stack-promtail
  namespace: prometheus
