apiVersion: v1
kind: Service
metadata:
  labels:
    app: loki
    release: loki-stack
  name: loki-stack-memberlist
  namespace: prometheus
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 7946
    protocol: TCP
    targetPort: memberlist-port
  publishNotReadyAddresses: true
  selector:
    app: loki
    release: loki-stack
  sessionAffinity: None
  type: ClusterIP
