apiVersion: v1
kind: Service
metadata:
  labels:
    app: loki
    release: loki-stack
    variant: headless
  name: loki-stack-headless
  namespace: prometheus
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-metrics
    port: 3100
    protocol: TCP
    targetPort: http-metrics
  selector:
    app: loki
    release: loki-stack
  sessionAffinity: None
  type: ClusterIP
