apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: loki-stack
    app.kubernetes.io/name: promtail
    app.kubernetes.io/version: 2.7.0
  name: loki-stack-promtail
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: loki-stack-promtail
subjects:
- kind: ServiceAccount
  name: loki-stack-promtail
  namespace: prometheus