config:
  modules:
    http_2xx:
      prober: http
      timeout: 8s
      http:
        tls_config:
          insecure_skip_verify: true
        valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
        follow_redirects: true
        preferred_ip_protocol: "ip4"