grafana:
  persistence:
    enabled: true
    storageClassName: managed-csi
    size: 10Gi
    accessModes:
      - ReadWriteOnce
  grafana.ini:
    auth.azuread:
      name: 'Azure AD'
      enabled: true           #Default is false
      allow_sign_up: true
      client_id: '<clientid>'
      client_secret: '<clientsecret>'
      scopes: 'openid email profile'
      auth_url: 'https://login.microsoftonline.com/<tenantid>/oauth2/v2.0/authorize'
      token_url: 'https://login.microsoftonline.com/<tenantid>/oauth2/v2.0/token'
      allowed_domains:
      allowed_groups:
      role_attribute_strict: false
    server:
      root_url: 'https://<url>'
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: managed-csi
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
