# statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: mongodb
spec:
  serviceName: mongodb-service
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      initContainers:
        - name: fix-keyfile-permissions
          image: busybox
          command: [
              "sh",
              "-c",
              mkdir -p /data/configdb
              rm -rf /data/configdb/keyfile
              cp /etc/mongo-keyfile/keyfile /data/configdb/keyfile
              chmod 600 /data/configdb/keyfile
              chown 999:999 /data/configdb/keyfile,
            ]
          volumeMounts:
            - name: mongodb-keyfile
              mountPath: /etc/mongo-keyfile
              readOnly: true
            - name: mongodb-persistent-storage
              mountPath: /data
      containers:
        - name: mongodb
          image: mongodb/mongodb-atlas-local
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /data/db
            - name: mongodb-keyfile
              mountPath: /data/configdb/keyfile
              subPath: keyfile
      volumes:
        - name: mongodb-persistent-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc
        - name: mongodb-keyfile
          secret:
            secretName: mongodb-keyfile
            items:
              - key: mongodb-keyfile
                path: keyfile
