# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mongodb
type: Opaque
data:
  username: cm9vdA== # "root" base64 encoded
  password: cGFzc3dvcmQxMjM= # "password123" base64 encoded
