apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: convertor-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - convertor.172.19.8.2.nip.io
    port:
      name: http
      number: 80
      protocol: HTTP
