apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: enable-backend-tls
  namespace: default
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: tls-backend
      sectionName: "443"
  validation:
    caCertificateRefs:
      - name: example-ca
        group: ""
        kind: ConfigMap
    hostname: www.example.com
