---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: appsecret
  namespace: test
spec:
  encryptedData:
    apikey: AgAWP9yGcUrcyqfFghi9Tyn71CRqOFORbw8xKn+SJhWdvSagOpZjcxhD/2Dwc7k4VOG19hvGfrRUDBfvDy7nIVYmmith9QW25aH/XvLyzgAZqjX6o/JHxdFV8P0/ypQyGWd0GyBMzapAwAHJI+lTl64fD1n+a+5bMZoJ9b+9KqKtFcQzVL1kjZKoB/8qAqYp9YB+p6XnBKMbX5+R3sgRavpdb/wTdnCx6DTh+VMgQY+MNVMbliFfQ6p87teH0xSgeaHLBpQZn8yAtNwwxW4Rb0PeXup9f69sLzseK+bZ2V89AQjpYNugSNbE28lED9DsxWddiFW1yzHFKeHGAIgz6pBaYdtQpx7TKazMmdNzoWnopl5LqF0akiVlzxRWay5vCceUWZBMIkUsLrsbohiiDIi5xHZpkBqomnKUZX85YkCUN54+es3DQzVVtnIVDLxaTV7AcZwdPVwD5rpugtojyX8muU5JRI1ByZrW+RByvBf7uqOus2DzGQva8FBuAvuDpVFg4ElnqakW55+82vGc1idUbWdDaxPRuJCZJjeVFl2dpkCUaFbrW56E6sBbQyY+adakT5BT+vhUQ7vGJ0X5rgQuW3I+uV51uwne3A2mZqfxOYv5hWeWXUQCyEwmnIgWbxkp5QBPhtOBRCW2btaWEZq9XQFEnR25El/CZNYVovBvyTsuZiYgjnONhe+Np8ShQZQT6va98i2eMLGsdDO9WCgnTraxarIhfyE+f3Eu3lcE2qWwK2abGQ==
  template:
    metadata:
      creationTimestamp: null
      name: appsecret
      namespace: test
    type: Opaque
