apiVersion: apps/v1
kind: Deployment 
metadata: #Dictionary
  name: httpd-deployment
spec: # Dictionary
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:  
    metadata: # Dictionary
      name: httpd
      labels: # Dictionary
        app: httpd  # Key value pairs
    spec:
      containers: # List
        - name: httpd
          image: httpd
          ports: 
            - containerPort: 80
    