{{- if .Values.appsecrets.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-test-sealed-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: test
  project: default
  source:
    path: argocd/app-secrets
    repoURL: https://github.com/dkr290/devops-projects.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
{{- end }}
