{{- if hasKey .Values "istioegressgateway" }}
{{- if .Values.istioegressgateway }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-egress
  namespace: argocd
spec:
  project: {{ .Values.istioegressgateway.project }}
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: gateway
    targetRevision: 1.21.0
    helm:
      releaseName: istio-egressgateway
      parameters:
      - name: service.type
        value: "ClusterIP"

  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: istio-ingress
  {{- if not .Values.istioegressgateway.syncPolicy.manual }}
  syncPolicy:
    automated:
    {{- with .Values.istioegressgateway.syncPolicy.automated }}
    {{- toYaml . | nindent 6 }}
    {{- end}}
  {{- end }}
{{- end }}
{{- end }}
