{{- if hasKey .Values "redisscaled" }}
{{- if .Values.redisscaled.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.redisscaled.name }}
  namespace: argocd
spec:
  project: {{ .Values.redisscaled.project }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.redisscaled.namespace }}
  source:
    path: {{ .Values.redisscaled.path }}
    repoURL: {{ .Values.redisscaled.repo }}
    targetRevision: {{ .Values.redisscaled.targetRevision }}
    helm:
      releaseName: db
      {{- with .Values.redisscaled.valueFiles }}
      valueFiles:
      {{- toYaml . | nindent 6 }}
      {{- end }}
  syncPolicy:
  {{- if not .Values.redisscaled.syncPolicy.manual }}
    automated:
    {{- with .Values.redisscaled.syncPolicy.automated }}
    {{- toYaml . | nindent 6 }}
    {{- end}}
  {{- end }}
    syncOptions:
    - PrunePropagationPolicy=foreground
{{- end }}
{{- end }}
