{{- if .Values.myapp.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: {{ .Values.myapp.project }}
  source:
    repoURL: https://github.com/dkr290/helm-charts.git
    path: myapp-istio
    targetRevision: {{ .Values.myapp.targetRevision }} 
    helm:
      releaseName: myapp
      {{- with .Values.myapp.valueFiles }}
      valueFiles:
      {{- toYaml . | nindent 6 }}
      {{- end }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: test
  {{- if not .Values.myapp.syncPolicy.manual }}
  syncPolicy:
    automated:
    {{- with .Values.myapp.syncPolicy.automated }}
    {{- toYaml . | nindent 6 }}
    {{- end}}
  {{- end }}
{{- end }}
