{{- if .Values.istioingressgateway.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  namespace: argocd
spec:
  project: {{ .Values.istioingressgateway.project }}
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: gateway
    targetRevision: 1.21.0
    helm:
      releaseName: istio-ingressgateway
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: istio-ingress
  {{- if not .Values.istioingressgateway.syncPolicy.manual }}
  syncPolicy:
    automated:
    {{- with .Values.istioingressgateway.syncPolicy.automated }}
    {{- toYaml . | nindent 6 }}
    {{- end}}
  {{- end }}
{{- end }}
