{{- if hasKey .Values "mongodb" }}
{{- if .Values.mongodb.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.mongodb.name }}
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.mongodb.project }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.mongodb.namespace }}
  source:
    path: {{ .Values.mongodb.path }}
    repoURL: {{ .Values.mongodb.repo }}
    targetRevision: {{ .Values.mongodb.targetRevision }}
  syncPolicy:
  {{- if not .Values.mongodb.syncPolicy.manual }}
    automated:
    {{- with .Values.mongodb.syncPolicy.automated }}
    {{- toYaml . | nindent 6 }}
    {{- end}}
  {{- end }}
    syncOptions:
    - PrunePropagationPolicy=foreground
{{- end }}
{{- end }}
