apiVersion: v1
kind: Secret
metadata:
  name: envoy-oci-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: gateway-helm
  url: oci://docker.io/envoyproxy
  enableOCI: "true"
