apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: myproject
  source:
    repoURL: https://github.com/dkr290/helm-charts.git
    path: myapp-istio 
    helm:
      releaseName: myapp
      valueFiles:
      - values.yaml
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: test
  syncPolicy:
    automated:
      selfHeal: true
      prune: true