apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-applicationset
  namespace: argocd
spec:
  generators:
     - list:
        elements:
          - name: nginx-gateway-fabric-helm
            namespace: nginx-gateway
            chart: nginx-gateway-fabric
            repoURL: https://your-helm-repo-url  # Replace with your Helm repo URL
            targetRevision: HEAD
          - name: nginx-gateway-api-standard
            namespace: nginx-gateway
            repoURL: https://github.com/nginxinc/nginx-gateway-fabric
            targetRevision: v1.3.0
            path: config/crd/gateway-api/standard  
  template:
    metadata:
      name: '{{`{{name}}`}}'
      labels:
        app: nginx-gateway   
    spec:
      project: default
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{`{{namespace}}`}}'
      source:
        repoURL: '{{`{{repoURL}}`}}'
        path: '{{`{{path}}`}}'
        targetRevision: '{{`{{targetRevision}}`}}'
        chart: '{{`{{chart}}`}}'  # This will only be used for the Helm application
     
