## it does not work well with helm + if etc
{{- if .Values.ngf }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-applicationset
  namespace: argocd
spec:
  generators:
     - list:
        elements:
          - name: nginx-gateway-fabric-helm
            namespace: nginx-gateway
            chart: nginx-gateway-fabric
            repoURL: oci://ghcr.io/nginxinc/charts/nginx-gateway-fabric  # Replace with your Helm repo URL
            targetRevision: HEAD
            releaseName: ngf
            # valueFiles:
            #   - values-dev.yaml
            parameters:
              - name: nginxGateway.replicaCount
                value: "3"  # Set the desired replica count here
          - name: nginx-gateway-api-standard
            namespace: nginx-gateway
            repoURL: https://github.com/nginxinc/nginx-gateway-fabric
            targetRevision: v1.3.0
            path: config/crd/gateway-api/standard  
  template:
    metadata:
      name: '{{`{{name}}`}}'
      namespace: '{{`{{namespace}}`}}'
      labels:
        app: nginx-gateway   
    spec:
      project: default
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{`{{namespace}}`}}'
      source:
        repoURL: '{{`{{repoURL}}`}}'
        targetRevision: '{{`{{targetRevision}}`}}'
         {{- if .chart }}
        chart: '{{`{{chart}}`}}'  # This will only be used for the Helm application
        helm:
          releaseName: '{{`{{releaseName}}`}}'
          parameters:
            {{- range .parameters }}
            - name: '{{.name}}'
              value: '{{.value}}'
            {{- end }}
        {{- else }}
        path: '{{`{{path}}`}}'
        {{- end }}
       {{- if not .Values.ngf.syncPolicy.manual }}
      syncPolicy:
        automated:
        {{- with .Values.ngf.syncPolicy.automated }}
        {{- toYaml . | nindent 10 }}
        {{- end}}
    {{- end }}
{{- end }}

