apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: argocd/sealed-secrets
    repoURL: https://github.com/dkr290/devops-projects.git
    targetRevision: HEAD