{{- if .Values.albingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: alb-class
  labels: 
    {{- include "gopypi.labels" . | nindent 4 }}
spec:
  controller: ingress.k8s.aws/alb
{{- end }}

