apiVersion: v1
data:
  oidc.config: |
    name: Azure
    issuer: https://login.microsoftonline.com/<tenantid>/v2.0
    clientID: ClientIDFortheapp
    clientSecret: $oidc.azure.clientSecret
    requestedIDTokenClaims:
      groups:
        essential: true
    requestedScopes:
      - openid
      - profile
      - email
  url: https://<argocdURL>/
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
