apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: quay.io/argoproj/argocd
    newTag: v2.6.1

# Note: Versions below 2.4.0 will not always work if trying to use AVP with Helm
# Fixed in https://github.com/argoproj/argo-cd/pull/9319
resources:
- https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.6.1
- cmp-plugin.yaml
- argocd-cm.yaml
- argocd-rbac-cm.yaml


patchesStrategicMerge:
- argocd-repo-server.yaml
