# Default values for helmbasics.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

releaseName: 
replicaCount:


resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

myapp:
  env: prod
  retail:
    enableFeature: true

podAnnotations:
  appName: myapp1
  appType: apiserver
  appTech: golang