apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/dkr290/devops-projects.git"
    path: argocd/argo-cd-apps
    targetRevision: main
    helm:
      valueFiles:
        - values-amazon.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
