apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-httproute
spec:
  parentRefs:
    - kind: Gateway
      group: gateway.networking.k8s.io
      name: eg
      namespace: envoy-gateway-system
  rules:
    - matches:
        - path:
            value: /argocd
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - group: ""
          kind: Service
          name: argocd-server
          port: 80
          weight: 1
