apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: secret1-deploy
  name: secret1-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret1-deploy

  template:
    metadata:
      creationTimestamp: null
      labels:
        app: secret1-deploy
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: secret1
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: secret-volume
          mountPath: "/etc/secret1"


