apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: secret-deploy
  name: secret-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-deploy

  template:
    metadata:
      creationTimestamp: null
      labels:
        app: secret-deploy
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: secret1
      containers:
      - image: nginx
        name: nginx
        env:
        - name: user
          valueFrom:
            secretKeyRef: 
              name: secret2
              key: user
        volumeMounts:
        - name: secret-volume
          mountPath: "/etc/secret1"