apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: secret2-deploy
  name: secret2-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret2-deploy

  template:
    metadata:
      creationTimestamp: null
      labels:
        app: secret2-deploy
    spec:
     
      containers:
      - image: nginx
        name: nginx
        env:
        - name: user
          valueFrom:
            secretKeyRef: 
              name: secret2
              key: user


