{{- if .Values.frontend.alb.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "frontend.alb" . }}
  labels: 
    {{- include "frontend.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.frontend.alb.customClass.enabled }}
    kubernetes.io/ingress.class: {{ .Values.frontend.alb.customClass.className }}
    {{- else }}
    {{- toYaml .Values.frontend.alb.annotations | nindent 4 }}
    {{- end }}
spec:
  rules:
   # - host: {{ .Values.frontend.alb.host }}
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "frontend.fullname" . }}
                port: 
                  number: {{ .Values.frontend.service.port }}

{{- end }}

