{{- if hasKey .Values "alb" }}
{{- if .Values.alb.enabled }}
{{- if .Values.alb.customClass.enabled }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.frontend.alb.className }}
  labels: 
    {{- include "frontend.alb" . | nindent 4 }}
spec:
  controller: ingress.k8s.aws/alb
{{- end }}
{{- end }}
{{- end }}

