{{- if hasKey .Values "envoy" }}
{{- if .Values.envoy.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.envoy.name }}
  namespace: argocd
spec:
  project: {{ .Values.envoy.project }}
  source:
    repoURL: {{ .Values.envoy.repo }}
    targetRevision: {{ .Values.envoy.targetRevision }}
    path: {{ .Values.envoy.path }}
    helm:
      releaseName: envoy-gateway
      {{- with .Values.envoy.valuesFiles }}
      valuesFiles:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.envoy.namespace }}
  syncPolicy:
  {{- if not .Values.envoy.syncPolicy.manual }}
    automated:
    {{- with .Values.envoy.syncPolicy.automated }}
      {{- toYaml . | nindent 6 }}
    {{- end}}
  {{- end }}
    syncOptions:
    - PrunePropagationPolicy=foreground
    - ServerSideApply=true
{{- end }}
{{- end }}
