apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-route
spec:
  parentRefs:
  - name: ext-shared-gw
    namespace: envoy-gateway-system
  hostnames:
  - "<somehostname>.eu-central-1.elb.amazonaws.com"
  rules:
  - backendRefs:
    - name: {{ include "currencyconf.fullname" . }}
      port: 5555
