spec:
  destination:
    server: 'https://kubernetes.default.svc'
  
myapp: 
  enabled: false
  syncPolicy:
    manual: false
    automated: 
      selfHeal: true
      prune: true
  targetRevision: main
  valueFiles:
  - values.yaml
