spec:
  destination:
    server: "https://kubernetes.default.svc"

appsecrets:
  enabled: false

redisscaled:
  enabled: true
  name: redis-scaled-app
  project: default
  path: central-repo/redis-scaled
  repo: https://github.com/dkr290/devops-projects.git
  namespace: default
  syncPolicy:
    manual: false
    automated:
      selfHeal: true
      prune: true
  targetRevision: main
  valueFiles:
    - values.yaml
