spec:
  destination:
    server: "https://kubernetes.default.svc"

###---------myapp application values -----------###
myapp:
  enabled: false
  syncPolicy:
    manual: false
    automated:
      selfHeal: true
      prune: true
  targetRevision: main
  project: myproject
  valueFiles:
    - values.yaml

appsecrets:
  enabled: false
## envoy gateway installation
envoy:
  enabled: false
  name: envoy
  project: default
  repo: docker.io/envoyproxy
  namespace: envoy-gateway-system
  targetRevision: v1.1.1
  syncPolicy:
    manual: true
    automated:
      selfHeal: true
      prune: true
  parameters:
    - name: deployment.replicas
      value: "3"
    - name: config.envoyGateway.logging.level.default
      value: info
## envoy gateway provisioning of class and resources

envoygwresource:
  enabled: false
  name: envoy-gateways-app
  project: default
  path: central-repo/envoy
  repo: https://github.com/dkr290/devops-projects.git
  namespace: envoy-gateway-system
  syncPolicy:
    manual: true
    automated:
      selfHeal: true
      prune: true
  targetRevision: main
  valueFiles:
    - values-dev.yaml

internalpypi:
  enabled: false
  name: internalpypi-app
  project: default
  path: central-repo/internal-pypi
  repo: https://github.com/dkr290/devops-projects.git
  namespace: default
  syncPolicy:
    manual: false
    automated:
      selfHeal: true
      prune: true
  targetRevision: main
  valueFiles:
    - values-dev.yaml

## this is applicable only with the envoy from backup
# envoy:
#   enabled: true
#   name: envoy
#   project: default
#   repo: https://github.com/dkr290/devops-projects.git
#   namespace: envoy-gateway-system
#   path: central-repo/envoy
#   targetRevision: main
#   syncPolicy:
#     manual: true
#     automated:
#       selfHeal: true
#       prune: true

# nginx gateway
# ngf:
#   syncPolicy:
#     manual: true
#     automated:
#       selfHeal: true
#       prune: true

# api-service
# apiservice:
#   enabled: true
#   syncPolicy:
#     manual: false
#     automated:
#       selfHeal: true
#       prune: true
#   targetRevision: main
#   project: default
#   valueFiles:
#     - values.yaml

# promgr
# promgr:
#   enabled: true
#   syncPolicy:
#     manual: true
#     automated:
#       selfHeal: true
#       prune: true
#   targetRevision: main
#   project: default
#   valueFiles:
#     - values.yaml
# envoy:
#   enabled: true
#   syncPolicy:
#     manual: false
#     automated:
#       selfHeal: true
#       prune: true
#   targetRevision: v1.0.1
#   project: default

#sealedsecrets:

###
guestbook:
  enabled: false
# istiobase:
#   enabled: true
#   syncPolicy:
#     manual: true
#     automated:
#       selfHeal: true
#       prune: true
#   project: default
# istiod:
#   enabled: true
#   syncPolicy:
#     manual: true
#     automated:
#       selfHeal: true
#       prune: true
#   project: default
# istioingressgateway:
#   enabled: true
#   syncPolicy:
#     manual: true
#     automated:
#       selfHeal: true
#       prune: true
#  project: default
# istioegressgateway:
#   enabled: true
#   syncPolicy:
#     manual: true
#     automated:
#       selfHeal: true
#       prune: true
#   project: default

## go tasks application
gotasks:
  enabled: true
  name: go-tasks-app
  project: default
  path: central-repo/go-tasks-ms
  repo: https://github.com/dkr290/devops-projects.git
  namespace: default
  syncPolicy:
    manual: false
    automated:
      selfHeal: true
      prune: true
  targetRevision: main
  valueFiles:
    - values.yaml
