spec:
  destination:
    server: "https://kubernetes.default.svc"

appsecrets:
  enabled: false

redisscaled:
  enabled: false
  name: redis-scaled-app
  project: default
  path: central-repo/redis-scaled
  repo: https://github.com/dkr290/devops-projects.git
  namespace: default
  syncPolicy:
    manual: false
    automated:
      selfHeal: true
      prune: true
  targetRevision: main
  valueFiles:
    - values.yaml

## go tasks application
gotasks:
  enabled: false
  name: go-tasks-app
  project: default
  path: central-repo/go-tasks-ms
  repo: https://github.com/dkr290/devops-projects.git
  namespace: default
  syncPolicy:
    manual: false
    automated:
      selfHeal: true
      prune: true
  targetRevision: main
  valueFiles:
    - values.yaml

## opensearch application
opensearch:
  enabled: true
  name: opensearch
  project: default
  path: central-repo/opensearch
  repo: https://github.com/dkr290/devops-projects.git
  namespace: opensearch
  syncPolicy:
    manual: true
    automated:
      selfHeal: true
      prune: true
  targetRevision: main
  valueFiles:
    - values-dev.yaml

## opensearch application
ollama:
  enabled: true
  name: ollama
  project: default
  path: central-repo/ollama
  repo: https://github.com/dkr290/devops-projects.git
  namespace: ollama
  syncPolicy:
    manual: true
    automated:
      selfHeal: true
      prune: true
  targetRevision: main
  valueFiles:
    - values.yaml

mongodb:
  enabled: false
  name: mongodb
  project: default
  path: central-repo/mongodb
  repo: https://github.com/dkr290/devops-projects.git
  namespace: mongodb
  syncPolicy:
    manual: true
    automated:
      selfHeal: true
      prune: true
  targetRevision: main
