spec:
  destination:
    server: "https://kubernetes.default.svc"

###---------myapp application values -----------###
myapp:
  enabled: false
  syncPolicy:
    manual: false
    automated:
      selfHeal: true
      prune: true
  targetRevision: main
  project: myproject
  valueFiles:
    - values.yaml

###
guestbook:
  enabled: false
