spec:
  destination:
    server: "https://kubernetes.default.svc"

###---------myapp application values -----------###
myapp:
  enabled: false
  syncPolicy:
    manual: false
    automated:
      selfHeal: true
      prune: true
  targetRevision: main
  project: myproject
  valueFiles:
    - values.yaml

appsecrets:
  enabled: false

# api-service
apiservice:
  enabled: true
  syncPolicy:
    manual: false
    automated:
      selfHeal: true
      prune: true
  targetRevision: main
  project: default
  valueFiles:
    - values.yaml
# promgr
promgr:
  enabled: true
  syncPolicy:
    manual: false
    automated:
      selfHeal: true
      prune: true
  targetRevision: main
  project: default
  valueFiles:
    - values.yaml
# envoy:
#   enabled: true
#   syncPolicy:
#     manual: false
#     automated:
#       selfHeal: true
#       prune: true
#   targetRevision: v1.0.1
#   project: default

###
guestbook:
  enabled: false
# istiobase:
#   enabled: true
#   syncPolicy:
#     manual: true
#     automated:
#       selfHeal: true
#       prune: true
#   project: default
# istiod:
#   enabled: true
#   syncPolicy:
#     manual: true
#     automated:
#       selfHeal: true
#       prune: true
#   project: default
# istioingressgateway:
#   enabled: true
#   syncPolicy:
#     manual: true
#     automated:
#       selfHeal: true
#       prune: true
#  project: default
# istioegressgateway:
#   enabled: true
#   syncPolicy:
#     manual: true
#     automated:
#       selfHeal: true
#       prune: true
#   project: default
