apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: grafana-eg
spec:
  gatewayClassName: exteg
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring

