apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-httproute
spec:
  parentRefs:
    - name: grafana-eg
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /grafana
      backendRefs:
        - name: promgr-grafana
          port: 80
          weight: 1
