apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.argo.events.httproute.name }}
  namespace: {{ .Values.argo.events.httproute.namespace }}
spec:
  {{- with .Values.argo.events.httproute }}
  hostnames:
    {{- toYaml .hostnames | nindent 4}}
  parentRefs:
    {{- toYaml .parentRefs | nindent 4}}
  {{- end }}
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: {{ .Values.argo.events.eventSourceName }}-eventsource-svc
          port: {{ index  .Values.argo.events.eventsource.service.ports 0 "port" }}
          weight: 1
      matches:
        - path:
            value: {{ .Values.argo.events.eventsource.webhook.test.endpoint }}
            type: PathPrefix
      timeouts:
        request: 300s
