apiVersion: apps/v1
kind: Deployment 
metadata: #Dictionary
  name: goappv1-deployment
spec: # Dictionary
  replicas: 2
  selector:
    matchLabels:
      app: goappv1
  template:  
    metadata: # Dictionary
      name: goappv1
      labels: # Dictionary
        app: goappv1  # Key value pairs
    spec:
      containers: # List
        - name: goappv1
          image: ghcr.io/dkr290/devops-projects/goappv1:latest
          ports: 
            - containerPort: 8080
    