apiVersion: v1
kind: Service 
metadata:
  name: goappv1-lb-service
spec:
  type: LoadBalancer # ClusterIp, # NodePort
  selector:
    app: goappv1
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 8080 # Container Port