apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: qdrant-gateway
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      protocol: HTTP
      port: 6333
    - name: grpc
      protocol: grpc
      port: 6334
    - name: p2p
      protocol: p2p 
      port: 6335


