{{- if .Values.apiroute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.apiroute.name }}
spec:
  parentRefs:
    - name: qdrant-gateway
  hostnames:
  {{- range .Values.apiroute.hostnames }}
    - {{ .hostname }}
  {{- end }}
  rules:
  {{- range .Values.apiroute.hostnames }}
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: {{ .backendRefs.name }}
          port: {{ .backendRefs.port }}
          weight: {{ .backendRefs.weight }}
  {{- end }}
{{- end }}
