{{- if .Values.apiroute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.apiroute.name }}
spec:
  parentRefs:
    - name: default-gateway
      namespace: envoy-gateway-system
  rules:
    {{- toYaml .Values.apiroute.rules | nindent 4 }}

{{- end }}
