apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.envoygateway.gatewayname }}-preview
spec:
  gatewayClassName: {{ .Values.envoygateway.class }}
  listeners:
    - name: http
      protocol: HTTP
      port: {{ .Values.envoygateway.httpportPreview }}
