apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.httproute.name }}-preview
spec:
  parentRefs:
    - name: {{.Values.envoygateway.gatewayname }}-preview
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: goapp-service-preview
          port: 8080
          weight: 1
