apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.httproute.name }}
spec:
  parentRefs:
    - name: {{.Values.envoygateway.gatewayname }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: goapp-service
          port: 8080
          weight: 1
