# Default values for myfirstchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


deployment:
  name: hekmdeployment
  replicaCount: 1
  image:
    app: nginx
    version: latest



service:
  name: helmservice
  type: ClusterIP
  port: 80
  targetPort: 80
  nodePort: 31239

