customRules:
  rules-custom.yaml: |-

    - rule: Terminal shell in container
      desc: A shell was used as the entrypoint/exec point into a container with an attached terminal.
      condition: >
        spawned_process and container
        and shell_procs and proc.tty != 0
        and container_entrypoint
        and not user_expected_terminal_shell_in_container_conditions
      output: >
        time=%evt.time,user=%user.name,%container.name,%container.id
        shell=%proc.name parent=%proc.pname cmdline=%proc.cmdline pid=%proc.pid terminal=%proc.tty container_id=%container.id image=%container.image.repository)
      priority: WARNING

    - rule: shell_in_container
      desc: notice shell activity within a container
      condition: >
        evt.type = execve and 
        evt.dir = < and 
        container.id != host and 
        proc.name = bash    
      output: >
        shell in a container 
        (user=%user.name container_id=%container.id container_name=%container.name 
        shell=%proc.name parent=%proc.pname cmdline=%proc.cmdline)    
      priority: WARNING