apiVersion: v1
kind: Service
metadata:
  name: {{ include "web1.fullname" . }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4}}
  {{- end }}
  labels:
    {{- include "web1.labels" . | nindent 4 }}
  
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "web1.selectorLabels" . | nindent 4 }}
