apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-appgw
  labels:
    app: nginx-appgw
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-appgw
  template:
    metadata:
      labels:
        app: nginx-appgw
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-appgw-service
spec:
  selector:
    app: nginx-appgw
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: appgw
  annotations:
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          service:
            name: nginx-appgw-service
            port:
              number: 80
        pathType: Exact
