cluster_name="gkedemo1"
business_division="operations"
environment="dev"
remove_default_node_pool=false
worker_nodes_disk_size = "30"
release_channel = "REGULAR"
kubernetes_version = "1.24.7-gke.900"
enable_vpc_router = false
enable_vpc_nat = false